<?php
/**
 * Created by PhpStorm.
 * User: huanglele
 * Date: 2016/8/28
 * Time: 下午 12:49
 */

namespace Home\Controller;


class DoubleColorBallController extends CommonController
{

    private $model ;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new \Common\Model\DoubleColorModel();
    }

    /**
     * 显示投注页面
     */
    public function index()
    {
        $current_times = $this->model->countCorrectTimes();
        $this->assign('current_times',$current_times);
        $this->display('index');
    }

    /**
     * 显示我的竞猜记录页面
     */
    public function myGuess()
    {

    }

    /**
     * 投注
     */
    public function buy()
    {
        $status =0;
        $times = I('post.times');
        $options = I('post.options');
        $info = $this->model->buy($options,$times);
        if($info===true){
            $info = '购买成功';
            $status = 1;
            $ret['coin'] = session('coin');
        }
        $ret['info'] = $info;
        $ret['status'] = $status;
        $this->ajaxReturn($ret);
    }

    /**
     * 显示帮助提示页面
     */
    public function help()
    {
        $this->display('help');
    }

}